### ISSUE TITLE
Tester class?

### ISSUE THREAD

**Issue by vihanb** [dishpanda/coffea#1]
Hi guys wondeirng if you u guys have a tester class. I would like to use interface and recursion to do subclass for bankaccount tester thanks

**Comment by siddhantsharma301** [comment]
not yet, currently working on it. thanks for your time though.

**Comment by orebitt** [comment]
Hi guys wondeirng if you u guys have a tester class. I would like to use interface and recursion to do subclass for bankaccount tester thanks

**Comment by vihanb** [comment]
![5B3D2247-286D-4294-86D8-303F76947142](https://user-images.githubusercontent.com/15314511/57800539-7e100900-7706-11e9-849d-257cebc17129.jpeg)

**Comment by siddhantsharma301** [comment]
![image](https://user-images.githubusercontent.com/47306418/58121823-1e5da600-7bbd-11e9-8228-53c88f27147b.png)
